# Generated by Django 2.2.4 on 2020-11-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_autor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_pulbicacion',
            new_name='fecha_publicacion',
        ),
    ]
