# Generated by Django 2.2.4 on 2020-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_auto_20201127_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor', verbose_name='Autor(es)'),
        ),
    ]
