# Generated by Django 3.1.3 on 2020-12-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20201127_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='autor',
            unique_together={('apellido', 'nombre')},
        ),
    ]
