# Generated by Django 3.1.3 on 2021-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
